### ISSUE TITLE
How to modify subscription ACLs is not documented

### ISSUE THREAD

**Issue by tofu-rocketry** [ARGOeu/argo-messaging#235]
Unlike the [docs on topics](http://argoeu.github.io/messaging/v1/api_topics/#post-modify-acl-of-a-given-topic), the [subscription docs](http://argoeu.github.io/messaging/v1/api_subs/) do not show how to modify their ACLs.

**Comment by themiszamani** [comment]
Dear @tofu-rocketry  (Adrian) 

Thank you for informing us about it. 
We have just updated the documentation ( #236 ) with information about how to modify the ACL's.

Best
Themis

**Comment by tofu-rocketry** [comment]
Ok, thanks. When do the documentation pages get rebuilt?

**Comment by tofu-rocketry** [comment]
How come the published documentation is still not showing the update?

**Comment by themiszamani** [comment]
Topics
 - http://argoeu-devel.github.io/messaging/v1/api_topics/#get-list-acl-of-a-given-topic
 - http://argoeu-devel.github.io/messaging/v1/api_topics/#post-modify-acl-of-a-given-topic

Subscription
 - http://argoeu-devel.github.io/messaging/v1/api_subs/#post-modify-acl-of-a-given-subscription

**Comment by tofu-rocketry** [comment]
Oh, that's on the `devel` documentation - that's why I couldn't find it.
