### ISSUE TITLE
Modify Offsets documentation not clear

### ISSUE THREAD

**Issue by tofu-rocketry** [ARGOeu/argo-messaging#382]
The section on modifying offsets has conflicting info: `offset_config` is listed, but the POST input shows `offset` - which should be used?

https://github.com/ARGOeu/argo-messaging/blob/629ca694d9118d8c6cde99273353f9d9c1e0bb24/website/docs/api_subs.md?plain=1#L750

**Comment by kaggis** [comment]
Yes it is an error in the documentation, thank you for pointing it out.

The correct parameter name is `offset`. An update has been made to address it.
