### ISSUE TITLE
Consumer guide documentation missing

### ISSUE THREAD

**Issue by pjcon** [ARGOeu/argo-messaging#389]
Returns 404

https://argoeu.github.io/messaging/v1/consumer.md

**Comment by themiszamani** [comment]
Dear @pjcon 
The guides are available from here 
https://argoeu.github.io/argo-messaging/docs/publisher
https://argoeu.github.io/argo-messaging/docs/subscriber_guide

**Comment by pjcon** [comment]
Thank you. I wasn't very clear here, this is when trying to access the documentation via the list down the left side, so it looks like it needs updating? https://argoeu.github.io/messaging/v1/

**Comment by themiszamani** [comment]
We moved to https://argoeu.github.io/argo-messaging/docs/ 
If you want you may see the API calls from here https://argoeu.github.io/argo-messaging/docs/api_auth
